./waf --run "lena-handover-many --simTime=10 timeToTrigger=40 hysteresis=1" > HO_40_1.txt
./waf --run "lena-handover-many --simTime=10 timeToTrigger=40 hysteresis=3" > HO_40_3.txt
./waf --run "lena-handover-many --simTime=10 timeToTrigger=40 hysteresis=5" > HO_40_5.txt
./waf --run "lena-handover-many --simTime=10 timeToTrigger=80 hysteresis=1" > HO_80_1.txt
./waf --run "lena-handover-many --simTime=10 timeToTrigger=80 hysteresis=3" > HO_80_3.txt
./waf --run "lena-handover-many --simTime=10 timeToTrigger=80 hysteresis=5" > HO_80_5.txt
./waf --run "lena-handover-many --simTime=10 timeToTrigger=256 hysteresis=1" > HO_256_1.txt
./waf --run "lena-handover-many --simTime=10 timeToTrigger=256 hysteresis=3" > HO_256_3.txt
./waf --run "lena-handover-many --simTime=10 timeToTrigger=256 hysteresis=5" > HO_256_5.txt
